name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

  deploy:
    name: Deployment
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Hosting Platform
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          # Install the Vercel CLI
          npm install -g vercel

          # Deploy your app to Vercel
          vercel --prod
